### ISSUE TITLE
 Explore android appbundle for apk signing+optimization

### ISSUE THREAD

**Issue by jleach** [bcgov/mobile-signing-service#18]
Explore android appbundle for apk signing+optimization

**Comment by cboreen** [comment]
All Android apps end up with this warning in the App Store:

Unoptimised APK

Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimising your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower installation success rates and take up storage on users' devices.

**Comment by MonicaG** [comment]
archiving this service
