### ISSUE TITLE
Create a permanent URL for the signing service

### ISSUE THREAD

**Issue by jleach** [bcgov/mobile-signing-service#20]
We need a permanent URL for the mobile signing service; its currently using one that is specific to the cluster. It should be a vanity URL so we don't need to be concerned with the cluster it runs on.

**Comment by jleach** [comment]
@ShellyXueHan Just occurred to me that the mobile signing serves should have a vanity URL so we can move it to a new cluster? Once we move it the URL will change because its using a pathfinder based URL.

**Comment by MonicaG** [comment]
archiving this service
