### ISSUE TITLE
MSS questions

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/mobile-signing-service#38]
### CICD:
- `secrets.OpenShiftToken` is it a service account token? does it expire?
- why do we need to build for node v10 and v12?
- don't we need a buildconfig template for api and web? github workflow is running `oc start-build <bc>` assuming there is a bc already?
- how does the `latest` image get tagged with `prod`? Manually after tested in dev?

### DB:
- we don't need a backup right? it's just for tracking job status

### agent:
- do i `do launchctl load -w` both of the plists: agent/config/launch/ca.bc.gov.developer.pfctl.plist

### General signing process:
- how's going with testing out iOS certificate? Can we do the same as Google?
- I'll start to get a team to test for existing google app signing migration

**Comment by jleach** [comment]
> ## MSS questions:
> ### CICD:
> * `secrets.OpenShiftToken` is it a service account token? does it expire?

That is the token from a SA. It will not expire and has very limited access. The manifest is stored in the repo.

> * why do we need to build for node v10 and v12?

I tend to build for the current version I'm developing agains and the previous for good measure. But not its not required. Only the current version is.

> * don't we need a buildconfig template for api and web? github workflow is running `oc start-build <bc>` assuming there is a bc already?

Yes, they should be stored in the repo. Standard s2i build or similar.

> * how does the `latest` image get tagged with `prod`? Manually after tested in dev?

Manually ATM.

> ### DB:
> * we don't need a backup right? it's just for tracking job status

None of the data is important. Its just needs to persist long enough for the `agent` to finish its work and report status back. So I don't think a backup is required. If we lost the database I'd just rebuild the schema empty.

> 
> ### agent:
> * do i `do launchctl load -w` both of the plists: agent/config/launch/ca.bc.gov.developer.pfctl.plist

Normally, yes. But when run as a Service/Damon in the background Xcode cannot get access to the account with access to iTunes to automatically update the provisioning profile (on demand). So, I've been starting it with `npm start` until this was solved.

> 
> ### General signing process:
> * how's going with testing out iOS certificate? Can we do the same as Google?

Good as reported during todays meeting.

> * I'll start to get a team to test for existing google app signing migration

Perf.
